# Generated by Django 4.1.3 on 2022-11-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='uni_id',
            field=models.CharField(default='n93v4YUHBFJLbnG5TWHx', max_length=20, null=True),
        ),
    ]
