# Generated by Django 4.1.3 on 2022-11-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_track_uni_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='musics',
            field=models.ManyToManyField(to='API.track'),
        ),
        migrations.AlterField(
            model_name='track',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='tracks/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='uni_id',
            field=models.CharField(default='sBgucRc9wUXPErLjweu6', max_length=20, null=True),
        ),
    ]
