# Generated by Django 4.1.3 on 2022-11-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_playlist_musics_alter_track_music_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='musics',
            new_name='tracks',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='musics',
            new_name='tracks',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='music',
            new_name='track',
        ),
        migrations.AlterField(
            model_name='track',
            name='uni_id',
            field=models.CharField(default='jq1WRWlah4FGVVArkriq', max_length=20, null=True),
        ),
    ]
