# Generated by Django 4.1.3 on 2022-11-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_rename_musics_album_tracks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='author',
            new_name='artist',
        ),
        migrations.AlterField(
            model_name='track',
            name='uni_id',
            field=models.CharField(default='JTszW91zDgfcX91EaWy6', max_length=20, null=True),
        ),
    ]
