# Generated by Django 4.1.3 on 2022-12-30 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0008_rename_author_track_artist_alter_track_uni_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedsongs',
            old_name='musics',
            new_name='tracks',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='thumnail',
            new_name='cover',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='User',
        ),
        migrations.RemoveField(
            model_name='track',
            name='thumnail',
        ),
        migrations.AddField(
            model_name='track',
            name='thumbnail',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='uni_id',
            field=models.CharField(default='Bw6Fsn79GBzIRYFySXNG', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_id', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserSetting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
