# Generated by Django 4.1.3 on 2022-12-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_alter_track_uni_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='uni_id',
            field=models.CharField(default='RczMIY62SV5yWOhI5HqF', max_length=20, null=True),
        ),
    ]
